export enum TipoDadosStorage {
  PERFIL_FINANCEIRO = 'PERFILFINANCEIRO',
  CADASTRO_COMPLETO = 'CADASTROCOMPLETO',
  CLIENTE_NAO_IDENTIFICADO = 'NAOIDENTIFICADO',
  NOVO_CLIENTE_CADASTRADO = 'SALVARNOVOCLIENTE',
  CADASTRAR_NOVO_CLIENTE = 'NOVOCPF'
}
