export enum TipoEntrega {
  ENDERECO = 'ENDERECO',
  ENDERECO_NOVO = 'ENDERECO_NOVO',
  RETIRA_DEPOSITO = 'RETIRA_DEPOSITO',
  RETIRA_LOJA = 'RETIRA_LOJA',
  RETIRA_OUTRA_LOJA = 'RETIRA_OUTRA_LOJA'
}
