export enum TipoCalculavel {
  CONJUNTO = 'CONJUNTO',
  MERCADORIA = 'MERCADORIA',
  GARANTIA = 'GARANTIA',
  SERVICO_TECNICO = 'SERVICO_TECNICO',
  FIQUE_SEGURO = 'FIQUE_SEGURO',
  MONTAGEM_MOVEIS = 'MONTAGEM_MOVEIS',
  VIDA_PROTEGIDA = 'VIDA_PROTEGIDA',
  PROTECAO_FINANCEIRA = 'PROTECAO_FINANCEIRA',
  CASA_PROTEGIDA = 'CASA_PROTEGIDA',
  ENTREGA = 'ENTREGA',
  CELULAR = 'CELULAR'
}
